---
title: "p8105_hw2_ec3663"
author: "Eunsuh Cho"
date: "2023-09-28"
output: github_document
---

```{r setup, include = FALSE}
library(tidyverse)
```


# Problem 1

## Cleaning the data

Cleaning the data in pols-month.csv

```{r clean pols-month.csv}
pols_month_df =
  read.csv("data/pols-month.csv") |> 
  janitor::clean_names() |> 
  separate(mon, into = c("year", "month", "day")) |> 
  mutate(
    month = case_match(
      month,
      "01" ~ "Jan",
      "02" ~ "Feb",
      "03" ~ "Mar",
      "04" ~ "Apr",
      "05" ~ "May",
      "06" ~ "Jun",
      "07" ~ "Jul",
      "08" ~ "Aug",
      "09" ~ "Sep",
      "10" ~ "Oct",
      "11" ~ "Nov",
      "12" ~ "Dec")) |> 
  mutate(
    president = case_when(
      prez_gop == 1 ~ "gop",
      prez_dem == 1 ~ "dem")) |> 
  select(-prez_dem, -prez_gop, -day) |> 
  relocate(year, month, president)
```

Cleaning the data in snp.csv

```{r clean_snp.csv}
snp_df =
  read.csv("data/snp.csv") |> 
  janitor::clean_names() |> 
  separate(date, into = c("month", "day", "year")) |> 
  mutate(
    month = case_match(
      month,
      "1" ~ "Jan",
      "2" ~ "Feb",
      "3" ~ "Mar",
      "4" ~ "Apr",
      "5" ~ "May",
      "6" ~ "Jun",
      "7" ~ "Jul",
      "8" ~ "Aug",
      "9" ~ "Sep",
      "10" ~ "Oct",
      "11" ~ "Nov",
      "12" ~ "Dec")) |> 
  select(-day) |> 
  relocate(year, month)
```

Cleaning the data in unemployment.csv

```{r clean_unemp.csv}
unemployment_df =
  read.csv("data/unemployment.csv") |> 
  pivot_longer(
    Jan:Dec,
    names_to = "month") |> 
  rename_with(tolower, everything())
```


